version: '3.8'

services:
  reservation-service:
    container_name: reservation-service
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - GPR_USER
        - GPR_TOKEN
    environment:
      - "SERVER_PORT=${SERVER_PORT:-8085}"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "DB_URL=jdbc:postgresql://reservation-db:5432/${DB_NAME:-reservation_db}"
      - "REDIS_HOST=reservation-redis"
      - "EUREKA_SERVER=http://host.docker.internal:8761/eureka/"
      - "KAFKA_SSL_PATH=/app/ssl/kafka.server.truststore.jks"
    ports:
      - "${SERVER_PORT:-8085}:${SERVER_PORT:-8085}"
    env_file:
      - .env
    volumes:
      - ./src/main/resources/ssl:/app/ssl:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pgsg-network

  db:
    image: postgres:17
    container_name: reservation-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-reservation_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-reservation-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pgsg-network

  redis:
    image: redis:7.2
    container_name: reservation-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pgsg-network

networks:
  pgsg-network:
    name: pgsg-network
    external: true

volumes:
  postgres-reservation-data:

secrets:
  GPR_USER:
    environment: GPR_USER
  GPR_TOKEN:
    environment: GPR_TOKEN