server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: reservation-service

  profiles:
    active: dev , kafka
    include: error, reservation-error

  # [필수 1] 설정 로드 순서
  # .env 파일을 먼저 읽고, 그 다음 외부 Config Server에 접속합니다.
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:configserver:${CONFIG_SERVER:http://34.50.50.170:13100}"

  # [필수 2] 로컬 우선순위 설정
  cloud:
    config:
      enabled: false
      allow-override: true
      override-none: false

  # [필수 3] 빈 중복 정의 허용
  main:
    allow-bean-definition-overriding: true

  # 데이터베이스 설정 (PostgreSQL)
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL:jdbc:postgresql://reservation-db:5432/reservation_db}

  # [필수 4] Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    properties:
      security.protocol: SSL
      ssl.truststore.location: "/app/ssl/kafka.server.truststore.jks"
      ssl.truststore.password: _aA123456
      ssl.endpoint.identification.algorithm: ""
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # [필수 5] Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

# [필수 6] 보안 및 유레카 설정
jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://host.docker.internal:8761/eureka/}
    registry-fetch-interval-seconds: 30

topics:
  reservation:
    completed: prod-reservation-completed