server:
  port: ${SERVER_PORT:8085}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: reservation-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev,kafka}

  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:configserver:${CONFIG_SERVER:http://34.50.50.170:13100}"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:34.64.35.152:9092,34.22.94.155:9092,34.50.28.59:9092}
    ssl:
      # Docker 환경(file:/app/...)과 로컬 환경(C:/...)을 환경 변수 하나로 제어합니다.
      trust-store-location: ${KAFKA_SSL_PATH:file:/app/ssl/kafka.server.truststore.jks}
      trust-store-password: _aA123456
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: ""

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    enabled: ${EUREKA_ENABLED:true} # 도커/로컬 상황에 따라 토글 가능
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

topics:
  reservation:
    completed: prod-reservation-completed
  product:
    created: prod-product-created