name: Deploy to GCP VM

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # GCP 인증
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # SSH 키 설정
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          ssh-keyscan -H 34.64.247.238 >> ~/.ssh/known_hosts

      # 프로젝트 핵심 파일만 VM으로 전송
      - name: 'Sync Project to VM'
        run: |
          mkdir -p deploy
          cp -r src deploy/
          cp build.gradle settings.gradle Dockerfile docker-compose.yml deploy/

          gcloud compute scp --recurse ./deploy/* zsx1397@reservation-service:~/app \
            --zone=asia-northeast3-a \
            --tunnel-through-iap \
            --ssh-key-file=~/.ssh/id_rsa \
            --quiet

      # VM에서 Docker Compose 실행
      - name: 'Docker Compose Up'
        run: |
          gcloud compute ssh zsx1397@reservation-service \
            --zone=asia-northeast3-a \
            --tunnel-through-iap \
            --ssh-key-file=~/.ssh/id_rsa \
            --quiet \
            --command="
              cd ~/app
          
              docker rm -f reservation-service || true
          
              docker rmi -f app-reservation-service || true
          
              docker-compose up -d --build --force-recreate
          
              sleep 5
              docker ps
          "