name: Deploy to GCP VM

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # 1. 서버로 파일 전송 (SCP)
      - name: 'Copy files to VM'
        run: |
          # --quiet를 넣어야 확인 질문 없이 자동으로 진행
          gcloud compute scp --recurse ./* reservation-service:~/app --zone=asia-northeast3-a --quiet

      # 2. 서버 접속 후 앱 재시작 (SSH)
      - name: 'SSH and Start App'
        run: |
          gcloud compute ssh reservation-service --zone=asia-northeast3-a --quiet --command="
            cd ~/app
            # 여기서부터는 서버 안에서 실행될 명령어
            ls -al
          "